export const NODE_ENV = "development"
export const DEBUG = true
// export const API_URI = process.env.API_URI || "http://localhost:8000/graphql/"
export const API_URI = "https://construirte-api-staging.herokuapp.com/graphql/"
// export const AUTH0_URI = "http://localhost:8000/graphql/login/auth0"
export const AUTH0_URI = "https://construirte-api-staging.herokuapp.com/login/auth0"
export const contratarPrimero = "step1"
export const contratarSegundo = "step2"
export const FEATURED_ID = "Q29sbGVjdGlvbjoz"
